/// Week-by-week pregnancy data — the core of the journey experience
class PregnancyWeekData {
  final int week;
  final String babySize;
  final String babySizeEmoji;
  final double babyLengthCm;
  final double babyWeightG;
  final String babyDevelopment;
  final List<String> commonSymptoms;
  final List<String> tips;
  final String trimester;

  const PregnancyWeekData({
    required this.week,
    required this.babySize,
    required this.babySizeEmoji,
    required this.babyLengthCm,
    required this.babyWeightG,
    required this.babyDevelopment,
    required this.commonSymptoms,
    required this.tips,
    required this.trimester,
  });

  static PregnancyWeekData getWeek(int week) {
    final clamped = week.clamp(4, 42);
    // Exact match
    if (_weekData.containsKey(clamped)) return _weekData[clamped]!;
    // Find closest week (prefer earlier)
    final keys = _weekData.keys.toList()..sort();
    int closest = keys.first;
    for (final k in keys) {
      if (k <= clamped) closest = k;
    }
    return _weekData[closest]!;
  }

  static final Map<int, PregnancyWeekData> _weekData = {
    4: const PregnancyWeekData(
      week: 4,
      babySize: 'Poppy seed',
      babySizeEmoji: '🫘',
      babyLengthCm: 0.1,
      babyWeightG: 0.04,
      babyDevelopment: 'The embryo has implanted in the uterus. The neural tube, which becomes the brain and spinal cord, is forming.',
      commonSymptoms: ['Missed period', 'Light spotting', 'Fatigue', 'Tender breasts'],
      tips: ['Start taking prenatal vitamins if you haven\'t already', 'Schedule your first prenatal appointment', 'Avoid alcohol and smoking'],
      trimester: 'First',
    ),
    8: const PregnancyWeekData(
      week: 8,
      babySize: 'Raspberry',
      babySizeEmoji: '🫐',
      babyLengthCm: 1.6,
      babyWeightG: 1.0,
      babyDevelopment: 'Baby\'s fingers and toes are forming. The heart is beating at about 150 beats per minute — twice as fast as yours!',
      commonSymptoms: ['Morning sickness', 'Fatigue', 'Frequent urination', 'Food aversions'],
      tips: ['Eat small, frequent meals to manage nausea', 'Stay hydrated', 'Rest when you can — your body is working hard'],
      trimester: 'First',
    ),
    12: const PregnancyWeekData(
      week: 12,
      babySize: 'Lime',
      babySizeEmoji: '🍋',
      babyLengthCm: 5.4,
      babyWeightG: 14.0,
      babyDevelopment: 'Baby can open and close their fists. Fingernails are forming. Vocal cords are developing.',
      commonSymptoms: ['Morning sickness easing', 'Growing belly', 'Dizziness', 'Increased energy'],
      tips: ['This is a common time to share the news!', 'First trimester screening can happen now', 'Start a pregnancy journal'],
      trimester: 'First',
    ),
    16: const PregnancyWeekData(
      week: 16,
      babySize: 'Avocado',
      babySizeEmoji: '🥑',
      babyLengthCm: 11.6,
      babyWeightG: 100.0,
      babyDevelopment: 'Baby can make facial expressions now. Their eyes can slowly move. The nervous system is functioning.',
      commonSymptoms: ['Round ligament pain', 'Nasal congestion', 'Backache', 'Possible first flutters'],
      tips: ['You might feel the first movements (quickening) soon', 'Consider a gender reveal if finding out', 'Start sleeping on your side'],
      trimester: 'Second',
    ),
    20: const PregnancyWeekData(
      week: 20,
      babySize: 'Banana',
      babySizeEmoji: '🍌',
      babyLengthCm: 25.6,
      babyWeightG: 300.0,
      babyDevelopment: 'Halfway there! Baby can hear sounds. They are developing a sleep-wake cycle. Vernix (waxy coating) covers the skin.',
      commonSymptoms: ['Visible baby movements', 'Leg cramps', 'Swelling in feet', 'Shortness of breath'],
      tips: ['Anatomy scan ultrasound is usually around now', 'Start thinking about a birth plan', 'Keep up with pelvic floor exercises'],
      trimester: 'Second',
    ),
    24: const PregnancyWeekData(
      week: 24,
      babySize: 'Cantaloupe',
      babySizeEmoji: '🍈',
      babyLengthCm: 30.0,
      babyWeightG: 600.0,
      babyDevelopment: 'Baby can hear your voice and respond to sounds. Their lungs are developing branches and surfactant. Taste buds are forming.',
      commonSymptoms: ['Braxton Hicks contractions', 'Backache', 'Swollen ankles', 'Linea nigra darkening'],
      tips: ['Talk and sing to your baby — they can hear you now!', 'Glucose screening test is coming up (24-28 weeks)', 'Start planning the nursery'],
      trimester: 'Second',
    ),
    28: const PregnancyWeekData(
      week: 28,
      babySize: 'Eggplant',
      babySizeEmoji: '🍆',
      babyLengthCm: 37.6,
      babyWeightG: 1000.0,
      babyDevelopment: 'Welcome to the third trimester! Baby can blink, dream, and has regular sleep cycles. Their brain is developing rapidly.',
      commonSymptoms: ['Shortness of breath', 'Trouble sleeping', 'Heartburn', 'Frequent urination returns'],
      tips: ['Start doing kick counts daily', 'Take a childbirth class', 'Tour the hospital or birth center', 'Begin packing your hospital bag'],
      trimester: 'Third',
    ),
    32: const PregnancyWeekData(
      week: 32,
      babySize: 'Squash',
      babySizeEmoji: '🎃',
      babyLengthCm: 42.4,
      babyWeightG: 1700.0,
      babyDevelopment: 'Baby is practicing breathing movements. Their bones are hardening (except the skull, which stays soft for delivery). They\'re gaining weight fast now.',
      commonSymptoms: ['Braxton Hicks more frequent', 'Heartburn', 'Leaking colostrum', 'Pelvic pressure'],
      tips: ['Finalize your birth plan', 'Pre-register at the hospital', 'Install the car seat', 'Consider a prenatal massage'],
      trimester: 'Third',
    ),
    36: const PregnancyWeekData(
      week: 36,
      babySize: 'Honeydew melon',
      babySizeEmoji: '🍈',
      babyLengthCm: 47.4,
      babyWeightG: 2600.0,
      babyDevelopment: 'Baby is running out of room! They\'re gaining about 28g per day. Most babies move to a head-down position by now.',
      commonSymptoms: ['Lightning crotch', 'Nesting instinct', 'Difficulty sleeping', 'Baby "dropping" lower'],
      tips: ['Hospital bag should be packed', 'Know the signs of labor', 'Freeze some meals for postpartum', 'Rest and enjoy these last weeks'],
      trimester: 'Third',
    ),
    40: const PregnancyWeekData(
      week: 40,
      babySize: 'Watermelon',
      babySizeEmoji: '🍉',
      babyLengthCm: 51.2,
      babyWeightG: 3400.0,
      babyDevelopment: 'Baby is fully developed and ready to meet you! Their skull bones are not yet fused — this helps them fit through the birth canal.',
      commonSymptoms: ['Mucus plug loss', 'Nesting energy', 'Irregular contractions', 'Anxiety and excitement'],
      tips: ['You\'re at your due date — baby will come when they\'re ready!', 'Call your doctor if contractions are 5 min apart for 1 hour', 'Try to stay calm and rested', 'You\'ve got this, mama!'],
      trimester: 'Third',
    ),

    // =====================================================
    // FIRST TRIMESTER fill-ins
    // =====================================================
    5: const PregnancyWeekData(
      week: 5,
      babySize: 'Sesame seed',
      babySizeEmoji: '🫘',
      babyLengthCm: 0.2,
      babyWeightG: 0.08,
      babyDevelopment: 'The heart begins to form and may start beating this week. The neural tube is closing. Tiny arm and leg buds appear. The embryo is growing about 1mm per day.',
      commonSymptoms: ['Positive pregnancy test', 'Breast tenderness', 'Fatigue deepens', 'Frequent urination starts', 'Mild cramping'],
      tips: ['Confirm pregnancy with your doctor', 'Prenatal vitamins with folic acid are essential', 'Cut out alcohol, smoking, and hot tubs', 'Rest when you need to — growing a human is hard work'],
      trimester: 'First',
    ),
    6: const PregnancyWeekData(
      week: 6,
      babySize: 'Sweet pea',
      babySizeEmoji: '🟢',
      babyLengthCm: 0.5,
      babyWeightG: 0.2,
      babyDevelopment: 'The heart beats at 100-150 beats per minute — often visible on ultrasound now. Eyes and ears are forming as tiny dark spots. Arm and leg buds are growing.',
      commonSymptoms: ['Morning sickness may begin', 'Heightened sense of smell', 'Food aversions', 'Mood swings', 'Frequent urination'],
      tips: ['Your first prenatal visit may happen this week', 'Eat crackers before getting out of bed for nausea', 'Small frequent meals beat 3 big ones', 'Ginger and vitamin B6 help with nausea'],
      trimester: 'First',
    ),
    7: const PregnancyWeekData(
      week: 7,
      babySize: 'Blueberry',
      babySizeEmoji: '🫐',
      babyLengthCm: 1.0,
      babyWeightG: 0.5,
      babyDevelopment: 'Baby\'s brain is growing rapidly — about 100 cells per minute. The mouth and tongue are forming. Hand and foot paddles appear. Nostrils form.',
      commonSymptoms: ['Full-blown morning sickness', 'Exhaustion', 'Larger, sore breasts', 'Heartburn may start', 'Emotional roller coaster'],
      tips: ['Stay hydrated — aim for 10 glasses of water daily', 'Eat what stays down; nutrition matters less than calories right now', 'Nap without guilt', 'Tell your workplace if your job involves hazardous exposure'],
      trimester: 'First',
    ),
    9: const PregnancyWeekData(
      week: 9,
      babySize: 'Grape',
      babySizeEmoji: '🍇',
      babyLengthCm: 2.3,
      babyWeightG: 2.0,
      babyDevelopment: 'Baby is now officially a fetus — no longer an embryo. All essential organs have begun to form. Tiny toes are visible. The tail is gone. Muscles begin to develop.',
      commonSymptoms: ['Nausea often peaks', 'Bloating', 'Constipation', 'Visible veins', 'Increased vaginal discharge (normal)'],
      tips: ['Genetic screening options can be discussed now', 'Eat fiber-rich foods for constipation', 'Comfortable shoes — feet may start swelling', 'Acupressure wristbands help nausea for some'],
      trimester: 'First',
    ),
    10: const PregnancyWeekData(
      week: 10,
      babySize: 'Strawberry',
      babySizeEmoji: '🍓',
      babyLengthCm: 3.1,
      babyWeightG: 4.0,
      babyDevelopment: 'Vital organs are formed and will grow and mature from here. Fingernails begin forming. Baby can bend limbs. Tooth buds appear in the gums.',
      commonSymptoms: ['Visible weight gain may begin', 'Round ligament twinges', 'Acne flare-ups', 'Vivid dreams', 'Slight belly bloat'],
      tips: ['NIPT (non-invasive prenatal testing) available from week 10', 'Start thinking about who to announce to first', 'Gentle exercise like walking is great now', 'Moisturize your belly — stretching skin needs love'],
      trimester: 'First',
    ),
    11: const PregnancyWeekData(
      week: 11,
      babySize: 'Fig',
      babySizeEmoji: '🫑',
      babyLengthCm: 4.1,
      babyWeightG: 7.0,
      babyDevelopment: 'Baby\'s head is still large relative to body. External genitals start to differentiate. Fingers are separating. Baby practices kicking and stretching (too small to feel).',
      commonSymptoms: ['Nausea may be easing', 'Energy returning slowly', 'Metallic taste may fade', 'Heightened libido for some'],
      tips: ['First trimester screening window (11-14 weeks)', 'Dental cleaning is safe and important', 'Sleep on your left side for best circulation', 'Still no need for maternity clothes — soft waistbands help'],
      trimester: 'First',
    ),
    13: const PregnancyWeekData(
      week: 13,
      babySize: 'Lemon',
      babySizeEmoji: '🍋',
      babyLengthCm: 7.4,
      babyWeightG: 23.0,
      babyDevelopment: 'Welcome to the LAST week of first trimester! Vocal cords are forming. Baby can put thumb in mouth. Intestines move from umbilical cord into the abdomen.',
      commonSymptoms: ['Lower miscarriage risk from here', 'Energy returning', 'Less nausea for most', 'Visible baby bump for some'],
      tips: ['Celebrate — the hardest trimester is almost done!', 'Time to share the news with close family if you want', 'Schedule the anatomy scan (around week 20)', 'Start thinking about maternity clothes shopping'],
      trimester: 'First',
    ),

    // =====================================================
    // SECOND TRIMESTER fill-ins
    // =====================================================
    14: const PregnancyWeekData(
      week: 14,
      babySize: 'Peach',
      babySizeEmoji: '🍑',
      babyLengthCm: 8.7,
      babyWeightG: 43.0,
      babyDevelopment: 'Welcome to the second trimester — often called the "golden" one! Baby can make facial expressions. Hair begins to grow. Liver and kidneys start functioning.',
      commonSymptoms: ['Energy returning', 'Bump starting to show', 'Round ligament pain', 'Nasal congestion (pregnancy rhinitis)'],
      tips: ['Start a pregnancy journal if you want', 'Schedule a babymoon while travel is easier', 'Keep up with hydration — you need 10+ glasses daily', 'Saline nasal spray helps congestion'],
      trimester: 'Second',
    ),
    15: const PregnancyWeekData(
      week: 15,
      babySize: 'Apple',
      babySizeEmoji: '🍎',
      babyLengthCm: 10.1,
      babyWeightG: 70.0,
      babyDevelopment: 'Baby can sense light through eyelids. Taste buds are developing. Skeletal system is hardening. Baby wiggles, though you may not feel it yet.',
      commonSymptoms: ['Rosy glow of pregnancy', 'Increased sex drive for some', 'Slight bleeding gums', 'Bigger appetite'],
      tips: ['Use a soft toothbrush — gums are sensitive', 'Prenatal yoga can start now', 'Eat 300 extra calories per day', 'Consider getting the flu shot (safe in pregnancy)'],
      trimester: 'Second',
    ),
    17: const PregnancyWeekData(
      week: 17,
      babySize: 'Pear',
      babySizeEmoji: '🍐',
      babyLengthCm: 13.0,
      babyWeightG: 140.0,
      babyDevelopment: 'Baby is starting to grow a protective layer of fat. Umbilical cord is thicker and stronger. Sweat glands develop. Baby can hear loud noises from outside.',
      commonSymptoms: ['Heartburn', 'Increased appetite', 'Stuffy nose', 'Strange aches in hips and abdomen'],
      tips: ['Elevate head with pillows for heartburn', 'Start sleeping on your side (left is best)', 'Stretching helps round ligament pain', 'Start researching pediatricians'],
      trimester: 'Second',
    ),
    18: const PregnancyWeekData(
      week: 18,
      babySize: 'Bell pepper',
      babySizeEmoji: '🫑',
      babyLengthCm: 14.2,
      babyWeightG: 190.0,
      babyDevelopment: 'Baby is yawning and hiccupping. Ears have moved to final position. Myelin (nerve coating) starts to form. Baby is very active — you may feel first movements.',
      commonSymptoms: ['First flutters (quickening)', 'Dizziness when standing up', 'Swelling in feet', 'Backache'],
      tips: ['Get up slowly to avoid dizziness', 'Drink water — dehydration worsens dizziness', 'Take the big anatomy scan appointment around now-20 weeks', 'Talk to baby — they can hear you'],
      trimester: 'Second',
    ),
    19: const PregnancyWeekData(
      week: 19,
      babySize: 'Mango',
      babySizeEmoji: '🥭',
      babyLengthCm: 15.3,
      babyWeightG: 240.0,
      babyDevelopment: 'Vernix caseosa (white waxy coating) covers baby\'s skin for protection. Lanugo (fine hair) covers the body. Limbs are in proportion now.',
      commonSymptoms: ['Round ligament pain more common', 'Shortness of breath', 'Leg cramps at night', 'Skin changes (darker areolas)'],
      tips: ['Stretch calves before bed to prevent cramps', 'Bananas and magnesium help leg cramps', 'Don\'t skip meals — baby needs steady fuel', 'Moisturize belly — stretch marks may appear'],
      trimester: 'Second',
    ),
    21: const PregnancyWeekData(
      week: 21,
      babySize: 'Carrot',
      babySizeEmoji: '🥕',
      babyLengthCm: 26.7,
      babyWeightG: 360.0,
      babyDevelopment: 'Baby is producing meconium (first poop) already. Taste buds working — they taste flavors through amniotic fluid. Eyebrows and lids are forming.',
      commonSymptoms: ['Stronger kicks', 'Braxton Hicks may start', 'Swelling in hands and feet', 'Heartburn worsens'],
      tips: ['Track baby\'s movements daily (though not formal kick counts yet)', 'Remove rings if fingers swell', 'Eat small portions for heartburn', 'Rest with feet elevated'],
      trimester: 'Second',
    ),
    22: const PregnancyWeekData(
      week: 22,
      babySize: 'Papaya',
      babySizeEmoji: '🍈',
      babyLengthCm: 27.8,
      babyWeightG: 430.0,
      babyDevelopment: 'Baby looks like a miniature newborn now. Tooth buds are developing. Pancreas is developing. Baby is roughly 50% bigger than 2 weeks ago.',
      commonSymptoms: ['Visible belly movements', 'Larger breasts leaking colostrum for some', 'Stretch marks', 'Back pain'],
      tips: ['Start thinking about birth classes', 'Research birthing options', 'Maternity bras with nursing flaps save money later', 'Support pillow between knees when sleeping'],
      trimester: 'Second',
    ),
    23: const PregnancyWeekData(
      week: 23,
      babySize: 'Grapefruit',
      babySizeEmoji: '🍊',
      babyLengthCm: 28.9,
      babyWeightG: 500.0,
      babyDevelopment: 'Baby\'s lungs are developing surfactant. Inner ear is fully formed — baby has sense of balance. Baby can recognize your voice patterns.',
      commonSymptoms: ['Thicker hair', 'Faster-growing nails', 'Vivid dreams', 'Clumsiness'],
      tips: ['Avoid hot yoga, saunas, hot tubs', 'Take your time — balance is off', 'Keep walking — 30 min most days', 'Sign up for a prenatal class'],
      trimester: 'Second',
    ),
    25: const PregnancyWeekData(
      week: 25,
      babySize: 'Cauliflower',
      babySizeEmoji: '🥦',
      babyLengthCm: 34.6,
      babyWeightG: 660.0,
      babyDevelopment: 'Baby is practicing breathing (moving amniotic fluid in and out). Hair color and texture forming. Response to touch is now very strong.',
      commonSymptoms: ['Trouble sleeping', 'Pelvic pressure', 'Leg cramps', 'Hemorrhoids for some'],
      tips: ['Side sleep with pillow support', 'Cold witch hazel helps hemorrhoids', 'Kick counts are OK to start', 'Hydrate, hydrate, hydrate'],
      trimester: 'Second',
    ),
    26: const PregnancyWeekData(
      week: 26,
      babySize: 'Lettuce head',
      babySizeEmoji: '🥬',
      babyLengthCm: 35.6,
      babyWeightG: 760.0,
      babyDevelopment: 'Baby opens eyes for the first time. Alveoli (air sacs) develop in lungs. Brain waves become more mature. Baby has a grip reflex.',
      commonSymptoms: ['Braxton Hicks more noticeable', 'Carpal tunnel symptoms', 'Dizziness', 'Pregnancy brain (forgetfulness)'],
      tips: ['Glucose tolerance test coming up (24-28 weeks)', 'Write things down — you\'ll forget', 'Wrist splints help carpal tunnel at night', 'Sit down when feeling dizzy'],
      trimester: 'Second',
    ),
    27: const PregnancyWeekData(
      week: 27,
      babySize: 'Head of cabbage',
      babySizeEmoji: '🥬',
      babyLengthCm: 36.6,
      babyWeightG: 875.0,
      babyDevelopment: 'Last week of second trimester! Baby has regular sleep and wake cycles. Nervous system is developing rapidly. Baby can now taste sweet vs bitter.',
      commonSymptoms: ['Rib pain (baby kicking up)', 'Tailbone discomfort', 'Leaking breasts possible', 'Increased back pain'],
      tips: ['Tour the hospital or birth center', 'Start packing hospital bag list', 'Pelvic tilts ease back pain', 'Final trimester — you\'re 2/3 of the way!'],
      trimester: 'Second',
    ),

    // =====================================================
    // THIRD TRIMESTER fill-ins
    // =====================================================
    29: const PregnancyWeekData(
      week: 29,
      babySize: 'Butternut squash',
      babySizeEmoji: '🎃',
      babyLengthCm: 38.6,
      babyWeightG: 1150.0,
      babyDevelopment: 'Baby\'s muscles and lungs are maturing rapidly. Bones are absorbing lots of calcium. Baby\'s head is growing to make room for developing brain.',
      commonSymptoms: ['Shortness of breath', 'Heartburn worsens', 'Varicose veins', 'Swelling continues'],
      tips: ['Eat iron and protein daily', 'Count baby\'s kicks daily (10 in 2 hours)', 'Elevate legs to reduce swelling', 'Write out your birth plan'],
      trimester: 'Third',
    ),
    30: const PregnancyWeekData(
      week: 30,
      babySize: 'Cabbage',
      babySizeEmoji: '🥬',
      babyLengthCm: 39.9,
      babyWeightG: 1320.0,
      babyDevelopment: 'Baby\'s brain is developing folds and grooves. Lanugo (fine hair) is starting to disappear. Bone marrow makes red blood cells. Baby can hear you clearly.',
      commonSymptoms: ['Mood swings return', 'Waddling walk', 'Trouble getting comfortable', 'Fatigue returns'],
      tips: ['Sing and talk to baby daily', 'Hospital pre-registration if not done', 'Install car seat and check it', 'Rest when you can'],
      trimester: 'Third',
    ),
    31: const PregnancyWeekData(
      week: 31,
      babySize: 'Coconut',
      babySizeEmoji: '🥥',
      babyLengthCm: 41.1,
      babyWeightG: 1500.0,
      babyDevelopment: 'Baby is gaining weight fast — about 230g per week. Five senses are all working. Baby processes multiple stimuli at once now.',
      commonSymptoms: ['Leaky breasts', 'Pressure in pelvis', 'Braxton Hicks', 'Frequent urination'],
      tips: ['Nursing pads for breast leaks', 'Pelvic floor exercises (Kegels) daily', 'Know difference: Braxton Hicks vs real contractions', 'Pack partner\'s bag too'],
      trimester: 'Third',
    ),
    33: const PregnancyWeekData(
      week: 33,
      babySize: 'Pineapple',
      babySizeEmoji: '🍍',
      babyLengthCm: 43.7,
      babyWeightG: 1920.0,
      babyDevelopment: 'Baby\'s skull stays soft and flexible for birth. Amniotic fluid peaks this week. Baby\'s immune system is getting antibodies from you.',
      commonSymptoms: ['Clumsiness', 'Aches everywhere', 'Shortness of breath improving if baby drops', 'Braxton Hicks increasing'],
      tips: ['Finalize childcare arrangements', 'Freeze meals for after birth', 'Learn newborn CPR basics', 'Stock up on postpartum supplies'],
      trimester: 'Third',
    ),
    34: const PregnancyWeekData(
      week: 34,
      babySize: 'Cantaloupe',
      babySizeEmoji: '🍈',
      babyLengthCm: 45.0,
      babyWeightG: 2150.0,
      babyDevelopment: 'Baby\'s lungs are almost fully mature. Baby practices sucking and swallowing. Fingernails reach fingertips. Vernix thickens for the journey.',
      commonSymptoms: ['Leaking urine when coughing/sneezing', 'Baby kicks under ribs', 'Foot swelling', 'Extreme fatigue'],
      tips: ['Pads for bladder leaks — normal', 'Weekly doctor visits start around now', 'Practice breathing techniques for labor', 'Pre-register at hospital if possible'],
      trimester: 'Third',
    ),
    35: const PregnancyWeekData(
      week: 35,
      babySize: 'Honeydew',
      babySizeEmoji: '🍈',
      babyLengthCm: 46.2,
      babyWeightG: 2380.0,
      babyDevelopment: 'Baby is running out of room. Brain is still developing rapidly. Kidneys are fully developed. Liver can process some waste.',
      commonSymptoms: ['Pelvic pain', 'Difficulty sleeping', 'Nesting instinct', 'Group B strep test around now'],
      tips: ['Sleep whenever you can — naps count', 'GBS swab test — completely normal', 'Finalize hospital bag', 'Practice relaxation techniques'],
      trimester: 'Third',
    ),
    37: const PregnancyWeekData(
      week: 37,
      babySize: 'Bunch of Swiss chard',
      babySizeEmoji: '🥬',
      babyLengthCm: 48.6,
      babyWeightG: 2860.0,
      babyDevelopment: 'Baby is early term (official "full term" is 39 weeks). Lanugo is mostly gone. Baby can grasp firmly. Digestive system is ready.',
      commonSymptoms: ['Increased discharge (possible mucus plug)', 'Lightening (baby drops)', 'Pelvic pressure', 'Braxton Hicks frequent'],
      tips: ['Know signs of labor', 'Keep hospital bag by the door', 'Rest as much as possible', 'Stay hydrated'],
      trimester: 'Third',
    ),
    38: const PregnancyWeekData(
      week: 38,
      babySize: 'Leek',
      babySizeEmoji: '🥬',
      babyLengthCm: 49.8,
      babyWeightG: 3080.0,
      babyDevelopment: 'Baby has a firm grasp. Eye color at birth may change over first year. Vocal cords ready to cry. Body fat continues to build.',
      commonSymptoms: ['Loose bowel movements', 'Intense tiredness', 'Back pain', 'Emotional swings'],
      tips: ['Any day now is possible', 'Have a labor plan ready', 'Don\'t over-schedule last weeks', 'Try to enjoy quiet moments'],
      trimester: 'Third',
    ),
    39: const PregnancyWeekData(
      week: 39,
      babySize: 'Mini watermelon',
      babySizeEmoji: '🍉',
      babyLengthCm: 50.7,
      babyWeightG: 3290.0,
      babyDevelopment: 'Baby is officially FULL TERM. Every day in the womb now is a bonus for brain development. Baby is ready for life outside.',
      commonSymptoms: ['Feeling very uncomfortable', 'Frequent bathroom trips', 'Irregular contractions', 'Restlessness'],
      tips: ['Rest and conserve energy', 'Gentle walking may help labor start', 'Spicy food, acupressure — unproven but harmless', 'Trust your body'],
      trimester: 'Third',
    ),
    41: const PregnancyWeekData(
      week: 41,
      babySize: 'Watermelon',
      babySizeEmoji: '🍉',
      babyLengthCm: 51.5,
      babyWeightG: 3600.0,
      babyDevelopment: 'Baby is fully mature and ready. Skin may start to peel slightly (no more vernix). Hair continues to grow.',
      commonSymptoms: ['Extreme discomfort', 'Impatience', 'Everyone asking if baby is here yet', 'Emotional ups and downs'],
      tips: ['Doctor may discuss induction options', 'Non-stress test likely', 'Keep moving gently', 'Baby is coming soon — you\'re OK'],
      trimester: 'Third',
    ),
    42: const PregnancyWeekData(
      week: 42,
      babySize: 'Watermelon',
      babySizeEmoji: '🍉',
      babyLengthCm: 52.0,
      babyWeightG: 3700.0,
      babyDevelopment: 'Baby is post-term. Doctor will monitor closely. Fingernails and hair are long. Most babies are born by 42 weeks.',
      commonSymptoms: ['Done being pregnant', 'Anxiety about baby\'s size/wellbeing', 'Possibly being induced', 'Exhaustion'],
      tips: ['Induction is common and safe at 42 weeks', 'Non-stress tests check baby\'s wellbeing', 'Ask all your questions', 'You\'re about to meet your baby'],
      trimester: 'Third',
    ),
  };
}
